### ISSUE TITLE
## Hot topics API

### ISSUE THREAD

**Issue by Victoriaspurlieu** [Victoriaspurlieu/Legacy#24]
As a volunteer, I want to quickly search for trending topics to volunteer to so that I can select the link of hot topic when I’m stuck.

## Acceptance Criteria
- [x] index.html bootstrap carousel with 3 topics
- [x] app.js has a click function which will get the next 3 topics and hides the previous 3 topics
- [x] app.js has an ajax call to retrive the data from database

**Comment by ghost** [comment]
The trending topic successfully displays from TrendSpottr API , then passes that thru the PixaBay API , Per consensus of the team , this will be used like a jumbotron .
